#%RAML 1.0
title: export-homebridge
version: v1
baseUri: http://localhost:8111/api/{version}
/ping: 
    displayName: Ping Resource
    description: Example - http://localhost:52031/api/v1/ping
    get: 
        description: Test service providing an indication that the service is available.
        responses: 
            "200": 
                description: pong as a string
            "500": 
                description: for unanticipated or unknown issues encountered.
/config:
    displayName: Config Resource
    description: Example - http://localhost:52031/api/v1/config
    get:
        description: Fetch the current state of the service's configuration. 包括串口设置，频道范围，发射功率，网络类型，MTORR发送频率(间接由网络类型定义)，通知方式
        responses:
            "200":
                description: The service's configuration as JSON document
/metrics:
    displayName: Metrics Resource
    description: Example - http://localhost:52031/api/v1/metrics
    get:
        description: Fetch the current state of the service's metrics.
        responses:
            "200":
                description: The service's metrics as JSON document
/module:
    displayName: ZigBee Module Resource
    description: Example - http://localhost:52031/api/v1/module
    get:
        description: Fetch the current state of the ZigBee Module. 
        responses:
            "200":
                description: The ZigBee Module's infomation
                body: 
                    application/json: 
                        example: '{"moduletype":"EM357","protocolversion":4,"stacktype":4,"stackversion":"5.6.0"}'
/mesh:
    displayName: ZigBee Mesh Resource
    description: Example - http://localhost:52031/api/v1/mesh
    get:
        description: Fetch the current state of the ZigBee mesh. 获取PANID,网络类型，频道，发射功率
        responses:
            "200":
                description: The ZigBee mesh's infomation
                body: 
                    application/json: 
                        example: '{"panid":"35dd","expanid":"c44f123456789abc","channel":13}'
            "404": 
                description: if no ZigBee mesh exists
    put: 
        description: Create a ZigBee mesh using the default parameters or using the specific channel. 如果已有网络存在，则修改频道 channel=null 自动选择频道，txpower=null 使用默认发射功率 
        body: 
            application/json: 
                example: '{"channel":14}'
        responses: 
            "200": 
                description: The ZigBee mesh is created and return the ZigBee mesh's infomation
                body: 
                    application/json: 
                        example: '{"panid":"35dd","expanid":"c44f123456789abc","channel":13}'
            "400":
                description: Invalid parameter
    delete:
        description: Delete the ZigBee mesh.
        responses:
            "200":
                description: The ZigBee mesh is deleted
            "404": 
                description: if no ZigBee mesh exists
/mesh/permission:
    displayName: ZigBee Mesh Permit Join Resource
    description: Example - http://localhost:52031/api/v1/mesh/permission
    put: 
        description: 允许符合条件的设备入网，必须指定ps，duration=0表示关闭permission
        body: 
            application/json: 
                example: '{"duration":60,"passports":[{"ps":"inSona:IN-C01-MFP-SX","mac":"XXXXXXXXXXXX1234"}]}'
        responses: 
            "200": 
                description: The ZigBee mesh is created and return the ZigBee mesh's infomation
            "400":
                description: Invalid parameter
            "404": 
                description: if no ZigBee mesh exists
            "405": 
                description: NCP执行失败
/mesh/unicast:
    displayName: ZigBee Mesh Unicast Resource
    description: Example - http://localhost:52031/api/v1/mesh/unicast
    post: 
        description: Send a unicast. needconfirm=true表示发送成功后需要通知
        body: 
            application/json: 
                example: '{"needconfirm":true,"msg":{"mac":"a5d462139f07884e","profile":0x0106,"cluster":0x0006,"srcedp":10,"dstedp":10,"data":"mADwAfj3vRC1BEYA8N"}}'
        responses: 
            "200": 
                description: 报文成功发送，needconfirm=true时返回有效tag
            "400":
                description: Invalid parameter
            "404": 
                description: if no ZigBee mesh exists
            "405": 
                description: NCP执行失败
/products:
    displayName: ZigBee Product List Resource
    description: Example - http://localhost:52031/api/v1/products
    get:
        description: 获取支持的产品列表
        responses:
            "200":
                description: 获取所有支持的产品
                body: 
                    application/json: 
                        example: '[{"ps":"inSona:IN-C01-MFP-SX","smallicon":"res/insona-in-c01-mfp-sx.small.png","name":"inSona多功能开关面板"}]'
    post: 
        description: 添加支持的产品
        body: 
            application/json: 
                example: '[{"ps":"inSona:IN-C01-MFP-SX","smallicon":"res/insona-in-c01-mfp-sx.small.png","name":"inSona多功能开关面板"}]'
        responses: 
            "200": 
                description: The Product is added
            "400":
                description: Invalid parameter
/devices:
    displayName: ZigBee Device List Resource
    description: Example - http://localhost:52031/api/v1/devices
    get:
        description: Fetch the ZigBee mesh's permit join settings, include the remain seconds and the permit product string 
        responses:
            "200":
                description: 获取所有设备表中的设备
                body: 
                    application/json: 
                        example: '[{"ps":"inSona:IN-C01-MFP-SX","mac":"a5d462139f07884e","name":"主卧入口面板","onlined":true,"actived":true}]'
    post: 
        description: 添加设备, MAC可以使用'*'通配符，但只能放在头部，且尾部至少4位要明确，如"*4bce"，匹配通配符时，优先匹配尾部位数多的
        body: 
            application/json: 
                example: '[{"ps":"inSona:IN-C01-MFP-SX","mac":"a5d462139f07884e","name":"主卧入口面板"}]'
        responses: 
            "200": 
                description: The ZigBee Device is added
            "400":
                description: Invalid parameter
/devices/{addr}:
    displayName: ZigBee Device Resource with the MAC provided
    description: Example - http://localhost:52031/api/v1/devices/a5d462139f07884e
    get:
        description: 获取此设备信息，包括product string, MAC, name
        responses:
            "200":
                description: 成功获取
                body: 
                    application/json: 
                        example: '{"ps":"inSona:IN-C01-MFP-SX","mac":"a5d462139f07884e","name":"主卧入口面板","onlined":true,"actived":true}'
            "404": 
                description: if the device non-exists
    put: 
        description: 修改设备信息，只能修改name
        body: 
            application/json: 
                example: '{"name":"主卧入口面板"}'
        responses: 
            "200": 
                description: 成功修改设备信息
            "400":
                description: Invalid parameter
            "404": 
                description: if the device non-exists
    delete:
        description: Delete the ZigBee Device. 如果当时mesh是存在的，则在设备表中删除并在网络中剔除，如果mesh不存在，则只在设备表中删除
        responses:
            "200":
                description: The ZigBee Device is deleted
            "404": 
                description: if no ZigBee Device exists
